{{< include /preamble/commands.qmd >}}

# Probability {#sec-Probability}
Probability theory is the study of uncertainty and random events. It provides a framework for predicting the likelihood of different outcomes in a given situation. The foundation of probability theory begins with the concept of an experiment, which is any process that leads to an uncertain result—such as flipping a coin, rolling a die, or drawing a card. The sample space is the set of all possible outcomes of the experiment, and an event is any subset of this sample space.


## Sample Space {#sec-Sample_Space}
The sample space of an experiment, e.g. rolling a die once, is the set of all of the possible outcomes. In the example of rolling a six-sided die once, the sample space would be $\Omega = \{1, 2, 3, 4, 5, 6\}$, and each event $E \subseteq \Omega$. The probability that an event $E$ occurs is denoted $\Pr{E}$, where $0 \leq \Pr{E} \leq \Pr{\Omega} = 1$. On the contrary, the probability of an event not occurring is $\Pr{E^\mathrm{C}} = 1 - \Pr{E}$, where $E^\mathrm{C}$ is called the complement of $E$. For example, the probability of rolling a $4$ (E = $\{4\}$) on a fair six-sided die is $1/6$, and the probability of not rolling a $4$ ($E^\mathrm{C}$ = $\{1, 2, 3, 5, 6\}$) is $5/6$.

For some experiments, the sample space can be empty ($\Omega = \emptyset$), meaning that there are no possible outcomes. In such cases, the probability of any event is defined to be zero ($\Pr{\emptyset} = 0$), as there are no outcomes that can occur. On the contrary, if the sample space contains only one outcome ($\Omega = \{x\}$), then the probability of that outcome is defined to be one, as it is the only possible outcome that can occur. There also exists experiments where the sample space is infinite, such as experiments measuring the time until an event occurs.


## Probability Function {#sec-Probability_Function}
Probability is assigned to events as a number between $0$ and $1$, where $0$ indicates impossibility and $1$ indicates certainty - $\mathbb{P}: \mathcal{A} \to [0, 1]$ for $E \subseteq \mathcal{A}$. For example, the probability of rolling a $4$ (E = $\{4\}$) on a fair six-sided die is $1/6$. Some basic rules of probability include: the probability of the entire sample space $\Omega$ is 1; if two events are mutually exclusive (cannot happen at the same time), the probability that either occurs is the sum of their individual probabilities.

::: {.callout-tip collapse = true title = "Probability Arithmetics" #tip-Probability_Arithmetics}
$$
\begin{aligned}
    \Pr{E^\mathrm{C}} &= 1 - \Pr{E} \\
    \Pr{E_1 \setminus E_2} &= \Pr{E_1} - \Pr{E_1 \cap E_2} \\
    \Pr{E_1 \cup E_2} &= \Pr{E_1} + \Pr{E_2} - \Pr{E_1 \cap E_2} \\
    \Pr{E \cap E^\mathrm{C}} &= 0
\end{aligned}
$$

:::

### Conditional Probability
$$
\Pr{E_1 \mid E_2} = \frac{\Pr{E_1 \cap E_2}}{\Pr{E_2}}
$$

Two events are said to be independent if $\Pr{E_1 \cap E_2} = \Pr{E_1}\Pr{E_2}$ meaning that if $\Pr{E_2} > 0$, then $\Pr{E_1 \mid E_2} = \Pr{E_1}$.

### Law of Total Probability

#### Bayes Formula {#sec-Bayes_Formula}
$$
\Pr{E_2 \mid E_1} = \frac{\Pr{E_1 \mid E_2}\Pr{E_1}}{\Pr{E_2}}, \quad \Pr{E_2} \neq 0
$$