{{< include /preamble/commands.qmd >}}

# Linear Regression {#sec-Linear_Regression}
Linear regression is used to model the relationship between response- and exploratory variable(s). Linear regression is widely used, as it is simple to understand and interpret, and can be used for both prediction and inference. The linear regression model assumes that the relationship between the response- and exploratory variable(s) is linear, which means that the change in the response variable is proportional to the change in the exploratory variable(s).

Let $y$ be the response variable(s) and $X \cdot \alpha$ the system of exploratory variables with regression coefficients described by $\alpha$ also called fixed effects. As the name suggests, the relationship between the response- and exploratory variable(s) is assumed to be linear, which can be expressed as:
$$
y = X \cdot \alpha + \varepsilon
$$
where $X$ is the fixed effects design matrix, and $\varepsilon$ is the zero-mean error(s).

In the case of the simple linear regression, there is only one exploratory variable $x$, and the model can be expressed as: $y = \alpha_0 + \alpha_1 x + \varepsilon$, where $\alpha_0$ is the intercept at $x = 0$ and $\alpha_1$ is the slope of the line (how much $y$ changes for a one-unit change in $x$). The errors are assumed to be independent and identically distributed (i.i.d.) with a normal distribution.


## Shortcomings {.unnumbered}
That does not mean that the linear regression does not have its shortcomings. Firstly, the assumption of a linear relationship between the response- and exploratory variable(s). This might not be correct for some data. Even if the data assumes a linear relationship, if outliers of the response variable have a dispropotionate influence on the fixed effects, then these fixed effects might be misleading. Secondly, similar to other statistical models, the linear regression does not handle missing data very well, and some preprocessing techniques might have to be applied to ensure reliable results. Moreover, when including too many exploratory variables with respect to the data size, the linear regression is prone to overfitting, reducing the generalisation of the fit. The addition of more exploratory variables are also only additive, meaning that it is not able to handle more complex relationships between the response- and exploratory variable(s). Furthermore, the errors in the linear regression are assumed to be Gaussian (see @sec-Gaussian_Stochastic_Variable) with constant variance. Devations from this can affect the confidence intervals, and thus some hypotheses that depend on this assumption.

{{< include /Examples/Statistical_Models/Linear_Regression.qmd >}}


## Estimation {#sec-Linear_Regression_Estimation}
The estimation of the fixed effects $\alpha$ is commonly done using the method of least squares, which minimizes the sum of squared residuals (the differences between observed and predicted values).