{{< include /preamble/commands.qmd >}}

# Hazard function {#sec-Hazard_Function}
The hazard function $h$ describes the instantaneous risk of an event at a time $t$. The instantaneuos risk at a time $t$ is bounded between 0 and 1, where the sum over all $t$ is 1. Mathematically, in the discrete case, this instantaneous risk equals the number of events between $t$ and $t+\Delta t$ divided by the population size at risk at time $t$, divided by $\Delta t$. In the continuous case, the hazard function is given as
$$
\begin{aligned}
    h(t) &= \lambda(t)
    \\&= \lim_{\Delta t \to 0}\frac{\Pr{t \leq T < t + \Delta t \mid T \geq t}}{\Delta t}
\end{aligned}
$$

## Cumulative hazard function
The cumulative hazard function $H$ describes the cumulative hazard up until a time $t$.
$$
\begin{aligned}
    H(t) &= \int_0^t h(u)\,\textrm{d}u\\
    &= \ln{S(t)}
\end{aligned}
$$
As opposed to the survival function (see @sec-Survival_Function), the cumulative hazard function is monotonically increasing, i.e. $H(t_2) \leq H(t_1)$ for all $t_1 \geq t_2$.

## Hazard ratio {#Hazard_Ratio}
The hazard ratio (HR) is often utilized when there is a desire to compare the hazard in one group to the hazard in another.

Non-collapsable. Not a causal estimand

- $\textrm{HR} < 1$: increased survival probability, compared to reference

- $\textrm{HR} = 1$: No difference in survival probability, compared to reference

- $\textrm{HR} > 1$: decreased survival probability, compared to reference

::: {#rem-HR}
The confidence intervals for HRs are only symmetrical on the log-scale, and not the usually presented exp-scale.
:::

