{{< include /preamble/commands.qmd >}}

# Survival function {#sec-Survival_Function}
To describe how probable it is for a person to survive until some time $t$, we can utilize the concept of stochastic variables (see @sec-Stochastic_Variables). The CDF (see @sec-CDF) can be used to describe the probability that an event occurs prior to time $t$ - $\Pr{T \leq t}$. The CDF of the stochastic variable $T$ is often referred to as the cumulative incidence function (CIF) and can be expressed as
$$
\begin{aligned}
    F_T(t) &= \Pr{T \leq t} \\
    &= \int_0^t h(u) \cdot S(u) \,\mathrm{d}u
\end{aligned}
$$ {#eq-CIF}
where $S$ is the survival function and $h$ is the hazard function. However, in survival analysis the opposite is of interest - that a person has survived past time $t$. Thus, the survival function can be defined as
$$
\begin{aligned}
    S(t) &= 1 - F_T(t) \\
    &= \Pr{T > t} = \int_t^\infty f_T(x) \,\mathrm{d}x
\end{aligned}
$$
where $F_T$ is the CIF and $f_T$ the pdf of $T$. One of the proporties of the survival function is that it is monotonically decreasing, i.e. $S(t_2) \leq S(t_1)$ for all $t_1 \geq t_2$.

{{< include /Examples/Survival_Analysis/Survival_Function.qmd >}}
{{< include /Figures/Survival_Analysis/Survival_Curve.qmd >}}